server:
  port: 8083

msa:
  client:
    url:
      gateway: http://localhost:8080 # gateway 주소

spring:
  r2dbc:
    url: r2dbc:h2:mem:///lecture;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
    username: sa
    password:
    initialization-mode: always
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
debug: false
